"""MockWorld scenario for TriageRetryLoop (ADR-0063 W2).

Drives the loop end-to-end against ``FakeGitHub`` (the canonical PRPort
fake) to assert the load-bearing transitions:

* A parked issue under the retry cap is re-dispatched to ``find`` with a
  comment that carries the original parking reason.
* A parked issue at the retry cap is escalated to ``hitl-escalation``
  with the ``triage-retry-exhausted`` sub-label, leaving the original
  parked label intact.

Pattern: direct ``FakeGitHub`` + ``MockWorld.run_with_loops`` — mirrors
``test_memory_backlog_scenario.py``. The catalog builder lives in
``tests/scenarios/catalog/loop_registrations.py``.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from unittest.mock import MagicMock

import pytest

from tests.scenarios.fakes.mock_world import MockWorld
from tests.scenarios.helpers.loop_port_seeding import seed_ports as _seed_ports

pytestmark = pytest.mark.scenario_loops


_PARKED_BODY = (
    "## Needs More Information\n\n"
    "This issue doesn't have enough detail for HydraFlow to begin work.\n\n"
    "**Missing:**\n"
    "- Reproduction steps\n"
    "- Expected vs actual\n\n"
    "Please update the issue with more context.\n\n"
    "---\n*Generated by HydraFlow Triage*"
)


class TestTriageRetryScenario:
    """End-to-end behaviour of the autonomous re-triage chain."""

    async def test_first_retry_redispatches_to_find(self, tmp_path) -> None:
        """Below the cap: the parked label is removed and find is set."""
        world = MockWorld(tmp_path)
        world._github.add_issue(
            number=701,
            title="Vague bug report",
            body=_PARKED_BODY,
            labels=["hydraflow-parked"],
        )

        state = MagicMock()
        state.get_triage_retry_attempts.return_value = 0
        state.inc_triage_retry_attempts.return_value = 1
        state.get_triage_retry_last_attempt.return_value = ""
        # Empty attempt dict so reconcile loops are a no-op.
        data = MagicMock()
        data.triage_retry_attempts = {}
        state._data = data

        _seed_ports(world, triage_retry_state=state)

        results = await world.run_with_loops(["triage_retry"], cycles=1)

        assert results["triage_retry"]["retried"] == 1
        assert results["triage_retry"]["escalated"] == 0
        issue = world._github._issues[701]
        assert "hydraflow-find" in issue.labels
        assert "hydraflow-parked" not in issue.labels
        # Re-dispatch posts a comment with the parking-reason context.
        retry_comments = [
            body
            for (target, body) in world._github._comments
            if target == 701 and "Auto-Retry" in body
        ]
        assert retry_comments, "expected a TriageRetryLoop comment"
        assert "Reproduction steps" in retry_comments[-1]

    async def test_three_attempts_then_escalation(self, tmp_path) -> None:
        """Counter at max → file hitl-escalation, leave parked label intact.

        The loop reads the counter from state (already at max) rather than
        running three live ticks because each tick respects the 24h floor.
        Driving the floor would require a fake clock; the counter-at-max
        path is what the escalation branch actually depends on.
        """
        world = MockWorld(tmp_path)
        world._github.add_issue(
            number=702,
            title="Still vague after three retries",
            body=_PARKED_BODY,
            labels=["hydraflow-parked"],
        )

        state = MagicMock()
        # At the cap — the next tick must escalate, not retry.
        state.get_triage_retry_attempts.return_value = 3
        state.inc_triage_retry_attempts.return_value = 4
        state.get_triage_retry_last_attempt.return_value = ""
        data = MagicMock()
        data.triage_retry_attempts = {"702": 3}
        state._data = data

        _seed_ports(world, triage_retry_state=state)

        results = await world.run_with_loops(["triage_retry"], cycles=1)

        assert results["triage_retry"]["escalated"] == 1
        assert results["triage_retry"]["retried"] == 0

        # Find the escalation issue — it carries hitl-escalation +
        # the triage-retry-exhausted sub-label.
        escalations = [
            issue
            for issue in world._github._issues.values()
            if "hydraflow-hitl-escalation" in issue.labels
            and "triage-retry-exhausted" in issue.labels
        ]
        assert len(escalations) == 1, (
            f"expected one HITL escalation; got {[i.number for i in escalations]}"
        )
        assert "#702" in escalations[0].body
        assert "Reproduction steps" in escalations[0].body

        # Original issue stays parked — the human now owns clarification.
        original = world._github._issues[702]
        assert "hydraflow-parked" in original.labels
        assert "hydraflow-find" not in original.labels

    async def test_recent_attempt_skipped_within_floor(self, tmp_path) -> None:
        """A parked issue retried 1h ago is left alone on the next tick."""
        world = MockWorld(tmp_path)
        world._github.add_issue(
            number=703,
            title="Just retried",
            body=_PARKED_BODY,
            labels=["hydraflow-parked"],
        )

        recent = (datetime.now(UTC) - timedelta(hours=1)).isoformat()
        state = MagicMock()
        state.get_triage_retry_attempts.return_value = 1
        state.get_triage_retry_last_attempt.return_value = recent
        data = MagicMock()
        data.triage_retry_attempts = {"703": 1}
        state._data = data

        _seed_ports(world, triage_retry_state=state)

        results = await world.run_with_loops(["triage_retry"], cycles=1)

        assert results["triage_retry"]["retried"] == 0
        assert results["triage_retry"]["escalated"] == 0
        assert results["triage_retry"]["skipped_recent"] == 1

        issue = world._github._issues[703]
        # Still parked, still not in find.
        assert "hydraflow-parked" in issue.labels
        assert "hydraflow-find" not in issue.labels
