"""Verification issue body formatting for post-merge human review."""

from __future__ import annotations

from models import GitHubIssue, JudgeResult, PRInfo

# GitHub issue body limit is 65,536 chars; reserve space for structured sections.
_MAX_INSTRUCTIONS_CHARS = 50_000


def format_verification_issue_body(
    judge_result: JudgeResult,
    issue: GitHubIssue,
    pr: PRInfo,
) -> str:
    """Build a markdown body for the verification issue.

    Includes links to the original issue and merged PR, per-criterion
    PASS/FAIL results, highlighted failures, and validated verification
    instructions for the human reviewer.
    """
    lines: list[str] = []

    # Header with links
    lines.append(f"## Verification: {issue.title}")
    lines.append("")
    lines.append(f"**Original issue:** #{issue.number}")
    lines.append(f"**Merged PR:** #{pr.number}")
    lines.append("")

    # Code-level results
    lines.append("### Code-Level Results")
    lines.append("")

    if judge_result.criteria:
        lines.append("| Criterion | Result | Details |")
        lines.append("|-----------|--------|---------|")
        for c in judge_result.criteria:
            icon = "\u2705 PASS" if c.passed else "\u274c FAIL"
            # Escape pipe characters in text to avoid breaking the table
            desc = c.description.replace("|", "\\|")
            details = c.details.replace("|", "\\|") if c.details else ""
            lines.append(f"| {desc} | {icon} | {details} |")
        lines.append("")

        # Summary note
        failed = judge_result.failed_criteria
        if failed:
            count = len(failed)
            noun = "criterion" if count == 1 else "criteria"
            lines.append(
                f"> \u26a0\ufe0f **{count} {noun} failed at code level** "
                "\u2014 pay extra attention to these during functional verification."
            )
            lines.append("")
        else:
            lines.append(
                "> \u2705 **All criteria passed at code level** "
                "\u2014 focus on functional verification."
            )
            lines.append("")
    else:
        lines.append("No acceptance criteria were evaluated.")
        lines.append("")

    # Verification instructions
    if judge_result.verification_instructions:
        lines.append("### Verification Instructions")
        lines.append("")
        instructions = judge_result.verification_instructions
        if len(instructions) > _MAX_INSTRUCTIONS_CHARS:
            instructions = instructions[:_MAX_INSTRUCTIONS_CHARS] + "\n\n*...truncated*"
        lines.append(instructions)
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by HydraFlow*")

    return "\n".join(lines)
