"""IssueBuilder — chainable, immutable test-data builder for GitHub issues."""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from itertools import count
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from tests.scenarios.fakes.mock_world import MockWorld

_auto_number = count(start=9000)


@dataclass(frozen=True)
class IssueBuilder:
    _number: int | None = None
    _title: str = "Test issue"
    _body: str = "Generated by IssueBuilder."
    _labels: tuple[str, ...] = ("hydraflow-find",)
    _author: str = "test-user"
    _comments: tuple[tuple[str, str], ...] = field(default_factory=tuple)

    def numbered(self, number: int) -> IssueBuilder:
        return replace(self, _number=number)

    def titled(self, title: str) -> IssueBuilder:
        return replace(self, _title=title)

    def bodied(self, body: str) -> IssueBuilder:
        return replace(self, _body=body)

    def labeled(self, *labels: str) -> IssueBuilder:
        """Replace current labels (use .also_labeled to append)."""
        return replace(self, _labels=labels)

    def also_labeled(self, *labels: str) -> IssueBuilder:
        return replace(self, _labels=(*self._labels, *labels))

    def authored_by(self, author: str) -> IssueBuilder:
        return replace(self, _author=author)

    def with_comment(self, body: str, *, by: str = "reviewer") -> IssueBuilder:
        return replace(self, _comments=(*self._comments, (by, body)))

    def at(self, world: MockWorld) -> Any:
        """Seed the issue in both ``world._issues`` (so run_pipeline iterates
        it) AND ``world.github`` (so PR/label inspection works).
        """
        number = self._number if self._number is not None else next(_auto_number)
        world.add_issue(
            number,
            self._title,
            self._body,
            labels=list(self._labels),
        )
        fake_issue = world.github.issue(number)
        if hasattr(fake_issue, "author"):
            setattr(fake_issue, "author", self._author)  # noqa: B010
        return fake_issue
