"""Render the bidirectional ADR ↔ module cross-reference."""

from __future__ import annotations

from collections import defaultdict

from arch._models import ADRRefIndex

_HEADER = "# ADR Cross-Reference\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.adr_cross_reference; do not hand-edit -->\n\n"
    "Bidirectional index between ADRs and the source modules they cite. "
    'Powers "Why this exists" backlinks across the site.\n\n'
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def render_adr_cross_reference(idx: ADRRefIndex) -> str:
    forward = sorted(idx.adr_to_modules, key=lambda r: r.adr_id)
    reverse: dict[str, list[str]] = defaultdict(list)
    for r in forward:
        for m in r.cited_modules:
            reverse[m].append(r.adr_id)

    fwd = "## ADR → Modules\n\n| ADR | Modules cited |\n|---|---|\n"
    fwd += "\n".join(
        f"| {r.adr_id} | {', '.join(f'`{m}`' for m in r.cited_modules) or '—'} |"
        for r in forward
    )

    rev = "\n\n## Module → ADRs\n\n| Module | Cited by |\n|---|---|\n"
    rev += "\n".join(
        f"| `{m}` | {', '.join(sorted(set(adrs)))} |"
        for m, adrs in sorted(reverse.items())
    )

    return _HEADER + _PREAMBLE + fwd + rev + _FOOTER
