"""Render the architecture changelog grouped by ISO week."""

from __future__ import annotations

from collections import defaultdict
from datetime import date

from arch._models import CommitInfo

_HEADER = "# Architecture Changelog (last 90 days)\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.changelog; do not hand-edit -->\n\n"
    "Commits touching `docs/arch/`, `docs/adr/`, `docs/wiki/`, "
    "`src/arch/`, or `mkdocs.yml`. Grouped by ISO week.\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def _iso_week(iso_date: str) -> str:
    y, m, d = (int(x) for x in iso_date.split("-"))
    yr, wk, _ = date(y, m, d).isocalendar()
    return f"{yr}-W{wk:02d}"


def render_changelog(commits: list[CommitInfo]) -> str:
    if not commits:
        return (
            _HEADER
            + _PREAMBLE
            + "_(empty — no recent architecture-touching commits)_\n"
            + _FOOTER
        )

    by_week: dict[str, list[CommitInfo]] = defaultdict(list)
    for c in commits:
        by_week[_iso_week(c.iso_date)].append(c)

    chunks = []
    for wk in sorted(by_week, reverse=True):
        chunks.append(f"## {wk}\n")
        for c in sorted(by_week[wk], key=lambda c: c.iso_date, reverse=True):
            pr = f" (#{c.pr_number})" if c.pr_number else ""
            chunks.append(f"- `{c.sha[:7]}` — {c.subject}{pr} *({c.iso_date})*")
        chunks.append("")
    return _HEADER + _PREAMBLE + "\n".join(chunks) + _FOOTER
