"""Render the event bus topology as a publishers/subscribers table."""

from __future__ import annotations

from arch._models import EventBusTopology

_HEADER = "# Event Bus Topology\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.event_bus; do not hand-edit -->\n\n"
    "Every `EventType` published or subscribed in `src/`. Events with "
    "no subscribers are flagged ⚠️ (likely dead).\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def render_event_bus(topo: EventBusTopology) -> str:
    if not topo.events:
        return _HEADER + _PREAMBLE + "_(no events discovered)_\n" + _FOOTER
    rows = []
    for e in topo.events:
        flag = " ⚠️" if not e.subscribers else ""
        pubs = "<br>".join(f"`{p}`" for p in e.publishers) or "—"
        subs = "<br>".join(f"`{s}`" for s in e.subscribers) or "—"
        rows.append(f"| **{e.event}**{flag} | {pubs} | {subs} |")
    table = "| Event | Publishers | Subscribers |\n|---|---|---|\n" + "\n".join(rows)
    return _HEADER + _PREAMBLE + table + _FOOTER
