"""Render the Functional Area Map: Mermaid clusters + per-area detail.

Pure function: (FunctionalAreas, list[LoopInfo], list[PortInfo]) -> str.
The hand-curated YAML is the source of grouping; live extractor outputs
are the source of membership truth. Items in the YAML that aren't found
by extractors are flagged inline (the coverage test in Task 6 is the
hard gate; the generator just visualizes).
"""

from __future__ import annotations

from arch._functional_areas_schema import FunctionalAreas
from arch._models import LoopInfo, PortInfo

_HEADER = "# Functional Area Map\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.functional_areas; do not hand-edit -->\n\n"
    "Top-level conceptual view of HydraFlow. Each cluster is a "
    "**functional area** — a coherent piece of what this machine does, "
    "curated in [`docs/arch/functional_areas.yml`](../functional_areas.yml). "
    "The loops/ports/modules inside each cluster are auto-joined from "
    "the live AST extractors. New loops or ports must be assigned to an "
    "area or `tests/architecture/test_functional_area_coverage.py` fails.\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def _safe(name: str) -> str:
    """Mermaid identifier: alphanumeric + underscore."""
    return "".join(c if c.isalnum() else "_" for c in name)


def _mermaid(
    fa: FunctionalAreas, *, known_loops: set[str], known_ports: set[str]
) -> str:
    lines = ["```mermaid", "flowchart LR"]
    for key, area in fa.areas.items():
        lines.append(f'    subgraph {key}["{area.label}"]')
        for ln in sorted(area.loops):
            tag = "" if ln in known_loops else ":::unknown"
            lines.append(f"        {_safe(key)}_{_safe(ln)}([{ln}]){tag}")
        for pn in sorted(area.ports):
            tag = "" if pn in known_ports else ":::unknown"
            lines.append(f"        {_safe(key)}_{_safe(pn)}[/{pn}/]{tag}")
        lines.append("    end")
    lines.append(
        "    classDef unknown stroke:#c00,stroke-width:2px,stroke-dasharray:4 2;"
    )
    lines.append("```")
    return "\n".join(lines)


def _detail_section(
    area,
    *,
    loop_index: dict[str, LoopInfo],
    port_index: dict[str, PortInfo],
) -> str:
    lines = [f"## {area.label}", "", area.description.strip(), ""]
    if area.loops:
        lines.append("**Loops**\n")
        for ln in sorted(area.loops):
            info = loop_index.get(ln)
            if info:
                lines.append(f"- `{ln}` — `{info.module}`")
            else:
                lines.append(
                    f"- ⚠️ `{ln}` — *unknown loop (not found by AST extractor)*"
                )
        lines.append("")
    if area.ports:
        lines.append("**Ports**\n")
        for pn in sorted(area.ports):
            info = port_index.get(pn)
            if info:
                lines.append(f"- `{pn}` — `{info.module}`")
            else:
                lines.append(f"- ⚠️ `{pn}` — *unknown port*")
        lines.append("")
    if area.modules:
        lines.append("**Module globs**\n")
        for g in area.modules:
            lines.append(f"- `{g}`")
        lines.append("")
    if area.related_adrs:
        adrs = ", ".join(f"`{a}`" for a in area.related_adrs)
        lines.append(f"**Related ADRs:** {adrs}\n")
    return "\n".join(lines)


def render_functional_areas(
    fa: FunctionalAreas,
    *,
    loops: list[LoopInfo],
    ports: list[PortInfo],
) -> str:
    loop_index = {info.name: info for info in loops}
    port_index = {info.name: info for info in ports}
    known_loops = set(loop_index)
    known_ports = set(port_index)

    body = _mermaid(fa, known_loops=known_loops, known_ports=known_ports) + "\n\n"
    body += "\n\n".join(
        _detail_section(a, loop_index=loop_index, port_index=port_index)
        for a in fa.areas.values()
    )
    return _HEADER + _PREAMBLE + body + _FOOTER
