"""Render the label state machine as Mermaid stateDiagram-v2."""

from __future__ import annotations

from arch._models import LabelStateMachine

_HEADER = "# Label State Machine\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.label_state; do not hand-edit -->\n\n"
    "Live transitions extracted from source. Compared against the "
    "Mermaid block in ADR-0002 by `tests/architecture/test_label_state_matches_adr0002.py`.\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def render_label_state(sm: LabelStateMachine) -> str:
    if not sm.transitions:
        return _HEADER + _PREAMBLE + "_(no transitions discovered)_\n" + _FOOTER
    lines = ["```mermaid", "stateDiagram-v2"]
    for t in sm.transitions:
        # Mermaid sanitization: replace hyphens (mermaid doesn't tolerate them as identifiers)
        a = t.from_state.replace("-", "_")
        b = t.to_state.replace("-", "_")
        label = f": {t.trigger}" if t.trigger else ""
        lines.append(f"    {a} --> {b}{label}")
    lines.append("```")
    return _HEADER + _PREAMBLE + "\n".join(lines) + _FOOTER
