"""Render the loop registry markdown table.

Pure function: list[LoopInfo] -> str. Output is byte-stable for byte-diff
comparison. Mermaid is not used here (a flat table is the right shape for
~30 rows of background loops).
"""

from __future__ import annotations

from arch._models import LoopInfo

_HEADER = "# Loop Registry\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.loop_registry; do not hand-edit -->\n\n"
    "All `BaseBackgroundLoop` subclasses discovered in `src/`. Generated "
    "from AST (no class introspection — see ADR-0049 for kill-switch convention).\n\n"
)
_TABLE_HEAD = (
    "| Loop | Module | Tick (s) | Kill Switch | Events | ADRs |\n"
    "|---|---|---|---|---|---|\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def _row(info: LoopInfo) -> str:
    tick = str(info.tick_interval_seconds) if info.tick_interval_seconds else "—"
    kill = f"`{info.kill_switch_var}`" if info.kill_switch_var else "—"
    events = ", ".join(info.event_subscriptions) or "—"
    adrs = ", ".join(info.adr_refs) or "—"
    module = f"`{info.module}`"
    return f"| **{info.name}** | {module} | {tick} | {kill} | {events} | {adrs} |"


def render_loop_registry(loops: list[LoopInfo]) -> str:
    sorted_loops = sorted(loops, key=lambda info: info.name)
    rows = "\n".join(_row(info) for info in sorted_loops)
    return _HEADER + _PREAMBLE + _TABLE_HEAD + rows + _FOOTER
