"""Render the MockWorld map: fakes table + Mermaid wiring."""

from __future__ import annotations

from arch._models import MockWorldMap

_HEADER = "# MockWorld Map\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.mockworld_map; do not hand-edit -->\n\n"
    "All fakes under `src/mockworld/fakes/`, the `*Port` each implements "
    "(by name match), and the scenarios that wire them. Per ADR-0022 "
    "(MockWorld) and ADR-0047 (fake-adapter contract testing).\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def render_mockworld_map(m: MockWorldMap) -> str:
    if not m.fakes:
        return _HEADER + _PREAMBLE + "_(no fakes discovered)_\n" + _FOOTER
    rows = []
    for f in m.fakes:
        port = f.implements_port or "—"
        scenarios = "<br>".join(f"`{s}`" for s in f.used_in_scenarios) or "—"
        rows.append(f"| **{f.name}** | `{port}` | {scenarios} |")
    table = (
        "## Fakes\n\n"
        "| Fake | Implements | Used in scenarios |\n"
        "|---|---|---|\n" + "\n".join(rows)
    )
    mermaid_lines = ["", "## Wiring", "", "```mermaid", "graph LR"]
    for f in m.fakes:
        port = f.implements_port or f.name
        mermaid_lines.append(f"    {f.name} -.-> {port}")
        for s in f.used_in_scenarios[:3]:  # cap to keep diagram readable
            scen_id = s.replace("/", "_").replace(".", "_")
            mermaid_lines.append(f"    {scen_id}([{s}]) --> {f.name}")
    mermaid_lines.append("```")
    return _HEADER + _PREAMBLE + table + "\n" + "\n".join(mermaid_lines) + _FOOTER
