"""Render the module import graph as Mermaid graph LR."""

from __future__ import annotations

from arch._models import ModuleGraph

_HEADER = "# Module Graph\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.module_graph; do not hand-edit -->\n\n"
    "Package-level import graph for `src/`. Edge weight = number of "
    "import statements aggregated across files.\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def _safe_id(name: str) -> str:
    return name.replace(".", "_")


def render_module_graph(g: ModuleGraph) -> str:
    if not g.nodes:
        return _HEADER + _PREAMBLE + "_(no modules discovered)_\n" + _FOOTER
    lines = ["```mermaid", "graph LR"]
    for n in g.nodes:
        lines.append(f'    {_safe_id(n.name)}["{n.name}"]')
    for e in g.edges:
        lines.append(
            f'    {_safe_id(e.from_module)} -- "{e.weight}" --> {_safe_id(e.to_module)}'
        )
    lines.append("```")
    return _HEADER + _PREAMBLE + "\n".join(lines) + _FOOTER
