"""Render the port map: Mermaid graph + per-port detail section."""

from __future__ import annotations

from arch._models import PortInfo

_HEADER = "# Port Map\n\n"
_PREAMBLE = (
    "<!-- generated by arch.generators.port_map; do not hand-edit -->\n\n"
    "Hexagonal boundaries. Each `*Port` Protocol with its concrete "
    "adapter(s) and fake (per ADR-0047). Ports without a fake are "
    "flagged ⚠️ — fakes are required for scenario testing.\n\n"
)
_FOOTER = "\n\n{{ARCH_FOOTER}}\n"


def _mermaid(ports: list[PortInfo]) -> str:
    lines = ["```mermaid", "graph LR"]
    for port in ports:
        for adapter in port.adapters:
            lines.append(f"    {port.name} --> {adapter.name}")
        if port.fake:
            lines.append(f"    {port.name} -.-> {port.fake.name}")
    lines.append("```")
    return "\n".join(lines)


def _detail_section(port: PortInfo) -> str:
    lines = [
        f"### {port.name}",
        "",
        f"- Module: `{port.module}`",
        f"- Methods: {', '.join(f'`{m}`' for m in port.methods) or '—'}",
    ]
    if port.adapters:
        lines.append("- Adapters:")
        for adapter in port.adapters:
            lines.append(f"  - `{adapter.name}` (`{adapter.module}`)")
    else:
        lines.append("- Adapters: —")
    if port.fake:
        lines.append(f"- Fake: `{port.fake.name}` (`{port.fake.module}`)")
    else:
        lines.append("- Fake: ⚠️ no fake (every Port needs a fake per ADR-0047)")
    return "\n".join(lines)


def render_port_map(ports: list[PortInfo]) -> str:
    sorted_ports = sorted(ports, key=lambda p: p.name)
    body = _mermaid(sorted_ports) + "\n\n## Details\n\n"
    body += "\n\n".join(_detail_section(p) for p in sorted_ports)
    return _HEADER + _PREAMBLE + body + _FOOTER
