"""GitPort — git CLI surface for scenario tests."""

from __future__ import annotations

from pathlib import Path
from typing import runtime_checkable

from typing_extensions import Protocol


@runtime_checkable
class GitPort(Protocol):
    async def worktree_add(
        self, path: Path, branch: str, *, new_branch: bool = False
    ) -> None: ...
    async def worktree_remove(self, path: Path, *, force: bool = False) -> None: ...
    async def worktree_prune(self) -> None: ...
    async def status(self, cwd: Path) -> str: ...
    async def commit(self, cwd: Path, message: str) -> str:
        """Return the new commit SHA."""
        ...

    async def push(self, cwd: Path, remote: str, branch: str) -> None: ...
    async def rev_parse(self, cwd: Path, ref: str) -> str: ...
    async def config_get(self, cwd: Path, key: str) -> str | None: ...
    async def config_unset(self, cwd: Path, key: str) -> None: ...
