"""Background worker loop — diagnostic self-healing for escalated issues."""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any

from base_background_loop import BaseBackgroundLoop, LoopDeps
from config import HydraFlowConfig
from events import EventType, HydraFlowEvent
from exception_classify import reraise_on_credit_or_bug
from models import AttemptRecord, Severity

if TYPE_CHECKING:
    from diagnostic_runner import DiagnosisResult, DiagnosticRunner
    from ports import PRPort
    from state import StateTracker
    from workspace import WorkspaceManager

logger = logging.getLogger("hydraflow.diagnostic_loop")


def _format_severity(severity: Severity) -> str:
    """Return a human-readable severity label."""
    labels = {
        Severity.P0_SECURITY: "P0 — Security",
        Severity.P1_BLOCKING: "P1 — Pipeline Blocking",
        Severity.P2_FUNCTIONAL: "P2 — Functional Bug",
        Severity.P3_WIRING: "P3 — Wiring / Config",
        Severity.P4_HOUSEKEEPING: "P4 — Housekeeping",
    }
    return labels.get(severity, str(severity))


def _format_diagnosis_comment(diagnosis: DiagnosisResult) -> str:
    """Format a diagnosis result as a markdown comment."""
    affected = (
        ", ".join(f"`{f}`" for f in diagnosis.affected_files)
        if diagnosis.affected_files
        else "_unknown_"
    )
    return (
        "## Diagnostic Analysis\n\n"
        f"**Severity:** {_format_severity(diagnosis.severity)}\n"
        f"**Root Cause:** {diagnosis.root_cause}\n"
        f"**Affected Files:** {affected}\n\n"
        "### Fix Plan\n"
        f"{diagnosis.fix_plan or '_No fix plan generated._'}\n\n"
        "### Human Guidance\n"
        f"{diagnosis.human_guidance or '_No guidance available._'}\n\n"
        "---\n"
        "*Generated by HydraFlow Diagnostic Agent*"
    )


class DiagnosticLoop(BaseBackgroundLoop):
    """Polls for ``hydraflow-diagnose`` issues and runs the two-stage diagnostic agent.

    Stage 1 (diagnose): Read-only analysis of root cause and severity.
    Stage 2 (fix): Attempt an automated fix inside the issue's worktree.

    On success the issue is transitioned to ``hydraflow-review``.
    On failure (not fixable, or attempts exhausted) the issue is escalated
    to ``hydraflow-hitl`` with the full diagnosis as a comment.
    """

    def __init__(
        self,
        config: HydraFlowConfig,
        runner: DiagnosticRunner,
        prs: PRPort,
        state: StateTracker,
        deps: LoopDeps,
        workspaces: WorkspaceManager | None = None,  # noqa: UP007
    ) -> None:
        super().__init__(
            worker_name="diagnostic",
            config=config,
            deps=deps,
        )
        self._runner = runner
        self._prs = prs
        self._state = state
        self._workspaces = workspaces

    def _get_default_interval(self) -> int:
        return self._config.diagnostic_interval

    async def _do_work(self) -> dict[str, Any] | None:
        """Poll for diagnosed issues and run the diagnostic pipeline."""
        try:
            issues = await self._prs.list_issues_by_label(
                self._config.diagnose_label[0]
            )
        except Exception as exc:
            reraise_on_credit_or_bug(exc)
            logger.warning("Failed to fetch issues for diagnostic check", exc_info=True)
            return {"processed": 0, "fixed": 0, "escalated": 0, "retried": 0}

        processed = 0
        escalated = 0
        fixed = 0
        retried = 0

        for raw_issue in issues:
            if self._stop_event.is_set():
                break
            issue_number = raw_issue.get("number", 0)
            if not issue_number:
                continue
            issue_title = raw_issue.get("title", "")
            issue_body = raw_issue.get("body", "") or ""
            outcome = await self._process_issue(issue_number, issue_title, issue_body)
            processed += 1
            if outcome == "fixed":
                fixed += 1
            elif outcome == "retry":
                retried += 1
            else:
                escalated += 1

        return {
            "processed": processed,
            "fixed": fixed,
            "escalated": escalated,
            "retried": retried,
        }

    async def _process_issue(  # noqa: PLR0911
        self,
        issue_number: int,
        issue_title: str,
        issue_body: str,
    ) -> str:
        """Run the full diagnostic pipeline for a single issue.

        Returns ``"fixed"`` when the issue was successfully repaired and
        transitioned to review, ``"retry"`` when the fix failed but attempts
        remain, or ``"escalated"`` when it was sent to HITL.
        """
        # --- Load escalation context ---
        context = self._state.get_escalation_context(issue_number)
        if context is None:
            logger.warning(
                "Diagnostic: no escalation context for issue #%d — escalating to HITL",
                issue_number,
            )
            await self._escalate_to_hitl(
                issue_number,
                comment=(
                    "## Diagnostic Analysis\n\n"
                    "**Severity:** P2 — Functional Bug\n"
                    "**Root Cause:** No escalation context found in state.\n"
                    "**Affected Files:** _unknown_\n\n"
                    "### Fix Plan\n"
                    "_Cannot diagnose without escalation context._\n\n"
                    "### Human Guidance\n"
                    "Please review this issue manually — the diagnostic agent "
                    "could not locate context for it.\n\n"
                    "---\n"
                    "*Generated by HydraFlow Diagnostic Agent*"
                ),
            )
            return "escalated"

        # --- Load previous attempts (used for context enrichment + limit check) ---
        attempts = self._state.get_diagnostic_attempts(issue_number)
        if attempts:
            context = context.model_copy(update={"previous_attempts": attempts})

        # --- Stage 1: Diagnose ---
        logger.info(
            "Diagnostic: running Stage 1 (diagnose) for issue #%d", issue_number
        )
        await self._publish_update(issue_number, "diagnosing")
        diagnosis = await self._runner.diagnose(
            issue_number, issue_title, issue_body, context
        )

        # Persist severity
        self._state.set_diagnosis_severity(issue_number, diagnosis.severity)

        diagnosis_comment = _format_diagnosis_comment(diagnosis)

        if not diagnosis.fixable:
            logger.info(
                "Diagnostic: issue #%d not fixable (severity=%s) — escalating to HITL",
                issue_number,
                diagnosis.severity,
            )
            await self._escalate_to_hitl(issue_number, comment=diagnosis_comment)
            return "escalated"

        # --- Check attempt limit ---
        if len(attempts) >= self._config.max_diagnostic_attempts:
            logger.info(
                "Diagnostic: issue #%d exhausted %d attempt(s) — escalating to HITL",
                issue_number,
                len(attempts),
            )
            await self._escalate_to_hitl(issue_number, comment=diagnosis_comment)
            return "escalated"

        # --- Stage 2: Fix ---
        logger.info(
            "Diagnostic: running Stage 2 (fix) for issue #%d (attempt %d of %d)",
            issue_number,
            len(attempts) + 1,
            self._config.max_diagnostic_attempts,
        )
        await self._publish_update(issue_number, "fixing")

        branch = f"agent/diag-{issue_number}"
        wt_path = self._config.workspace_path_for_issue(issue_number)

        # Create workspace if we have a manager and the path doesn't exist
        if self._workspaces is not None and not wt_path.exists():
            try:
                wt_path = await self._workspaces.create(issue_number, branch)
            except Exception:
                logger.exception(
                    "Diagnostic: workspace creation failed for issue #%d",
                    issue_number,
                )
                await self._escalate_to_hitl(issue_number, comment=diagnosis_comment)
                return "escalated"

        try:
            success, transcript = await self._runner.fix(
                issue_number, issue_title, issue_body, diagnosis, str(wt_path)
            )
        except Exception:
            logger.exception(
                "Diagnostic: runner.fix() crashed for issue #%d", issue_number
            )
            success, transcript = False, "runner.fix() crashed"
        finally:
            if self._workspaces is not None:
                try:
                    await self._workspaces.destroy(issue_number)
                except Exception:
                    logger.warning(
                        "Diagnostic: workspace cleanup failed for issue #%d",
                        issue_number,
                        exc_info=True,
                    )

        # Record this attempt regardless of outcome
        record = AttemptRecord(
            attempt_number=len(attempts) + 1,
            changes_made=success,
            error_summary=(
                "" if success else (transcript[:200] if transcript else "fix failed")
            ),
            timestamp=datetime.now(UTC).isoformat(),
        )
        self._state.add_diagnostic_attempt(issue_number, record)

        if success:
            logger.info(
                "Diagnostic: fix succeeded for issue #%d — transitioning to review",
                issue_number,
            )
            await self._prs.post_comment(
                issue_number,
                (
                    "## Diagnostic Fix Applied\n\n"
                    "The diagnostic agent successfully applied a fix.\n\n"
                    f"{diagnosis_comment}"
                ),
            )
            try:
                await self._prs.swap_pipeline_labels(
                    issue_number, self._config.review_label[0]
                )
            except Exception:
                logger.warning(
                    "Diagnostic: label swap to review failed for issue #%d "
                    "— fix was applied but issue may need manual label update",
                    issue_number,
                    exc_info=True,
                )
            await self._publish_update(issue_number, "fixed")
            return "fixed"

        # Fix failed — check if we still have attempts remaining after recording
        attempts_after = self._state.get_diagnostic_attempts(issue_number)
        if len(attempts_after) < self._config.max_diagnostic_attempts:
            # Will retry next cycle — leave on diagnose label
            logger.info(
                "Diagnostic: fix attempt %d failed for issue #%d — will retry next cycle",
                len(attempts_after),
                issue_number,
            )
            await self._publish_update(issue_number, "retry")
            return "retry"

        # All attempts exhausted after this failure
        logger.info(
            "Diagnostic: fix failed and attempts exhausted for issue #%d — escalating to HITL",
            issue_number,
        )
        await self._escalate_to_hitl(issue_number, comment=diagnosis_comment)
        return "escalated"

    async def _escalate_to_hitl(self, issue_number: int, *, comment: str) -> None:
        """Post the diagnosis comment and swap labels to HITL."""
        try:
            await self._prs.post_comment(issue_number, comment)
        except Exception:
            logger.warning(
                "Diagnostic: failed to post comment for issue #%d",
                issue_number,
                exc_info=True,
            )
        try:
            await self._prs.swap_pipeline_labels(
                issue_number, self._config.hitl_label[0]
            )
        except Exception:
            logger.warning(
                "Diagnostic: label swap to HITL failed for issue #%d "
                "— issue may need manual label update",
                issue_number,
                exc_info=True,
            )
        await self._publish_update(issue_number, "escalated")

    async def _publish_update(self, issue_number: int, status: str) -> None:
        """Publish a DIAGNOSTIC_UPDATE event for dashboard visibility."""
        await self._bus.publish(
            HydraFlowEvent(
                type=EventType.DIAGNOSTIC_UPDATE,
                data={"issue": issue_number, "status": status},
            )
        )
