"""Plan phase — run planning agents on issues and post results."""

from __future__ import annotations

import asyncio
import logging
import re
from typing import TYPE_CHECKING

from analysis import PlanAnalyzer
from config import HydraFlowConfig
from events import EventBus
from harness_insights import FailureCategory, HarnessInsightStore
from models import EpicGapReview, IssueOutcomeType, PipelineStage, PlanResult, Task
from phase_utils import (
    MemorySuggester,
    PipelineEscalator,
    _sentry_transaction,
    release_batch_in_flight,
    run_concurrent_batch,
    run_refilling_pool,
    store_lifecycle,
)
from planner import PlannerRunner
from research_runner import ResearchRunner
from state import StateTracker
from task_source import TaskTransitioner
from transcript_summarizer import TranscriptSummarizer

if TYPE_CHECKING:
    from beads_manager import BeadsManager
    from epic import EpicManager
    from hindsight import HindsightClient
    from issue_cache import IssueCache
    from memory_judge import MemoryJudge  # noqa: TCH004
    from ports import IssueStorePort, PRPort
    from repo_wiki import RepoWikiStore  # noqa: TCH004
    from wiki_compiler import WikiCompiler  # noqa: TCH004

logger = logging.getLogger("hydraflow.plan_phase")

# Minimum body length for auto-filed sub-issues discovered during planning.
_MIN_ISSUE_BODY_CHARS: int = 50


class PlanPhase:
    """Runs planning agents on issues and posts results."""

    def __init__(
        self,
        config: HydraFlowConfig,
        state: StateTracker,
        store: IssueStorePort,
        planners: PlannerRunner,
        prs: PRPort,
        event_bus: EventBus,
        stop_event: asyncio.Event,
        transcript_summarizer: TranscriptSummarizer | None = None,
        harness_insights: HarnessInsightStore | None = None,
        epic_manager: EpicManager | None = None,
        research_runner: ResearchRunner | None = None,
        beads_manager: BeadsManager | None = None,
        wiki_store: RepoWikiStore | None = None,
        wiki_compiler: WikiCompiler | None = None,
        hindsight: HindsightClient | None = None,
        judge: MemoryJudge | None = None,
        issue_cache: IssueCache | None = None,
    ) -> None:
        self._config = config
        self._state = state
        self._store = store
        self._planners = planners
        self._prs = prs
        self._transitioner: TaskTransitioner = prs
        self._bus = event_bus
        self._stop_event = stop_event
        self._summarizer = transcript_summarizer
        self._harness_insights = harness_insights
        self._epic_manager = epic_manager
        self._research_runner = research_runner
        self._beads_manager = beads_manager
        self._wiki_store = wiki_store
        self._wiki_compiler = wiki_compiler
        self._issue_cache = issue_cache
        self._suggest_memory = MemorySuggester(config, hindsight=hindsight, judge=judge)
        self._escalator = PipelineEscalator(
            state,
            prs,
            store,
            harness_insights,
            origin_label=config.planner_label[0],
            hitl_label=config.hitl_label[0],
            diagnose_label=config.diagnose_label[0],
            stage=PipelineStage.PLAN,
        )

    def _should_research(self) -> bool:
        """Return True if research should run before planning."""
        return self._research_runner is not None

    async def _handle_already_satisfied(self, issue: Task, result: PlanResult) -> bool:
        """Validate evidence and close issue as already-satisfied.

        Returns ``True`` if the issue was closed, ``False`` if evidence validation
        failed (caller should fall through to plan failure handling).
        """
        validation_errors = PlannerRunner.validate_already_satisfied_evidence(
            result.summary,
            issue_body=issue.body,
            repo_root=self._config.repo_root,
        )
        if validation_errors:
            error_list = "\n".join(f"- {e}" for e in validation_errors)
            await self._transitioner.post_comment(
                issue.id,
                f"## Already-Satisfied Evidence Rejected\n\n"
                f"The planner claimed this issue is already satisfied, but the "
                f"evidence failed validation:\n\n{error_list}\n\n"
                f"The issue will be escalated for review.\n\n"
                f"---\n"
                f"*Generated by HydraFlow Planner*",
            )
            result.already_satisfied = False
            result.success = False
            result.retry_attempted = True
            result.validation_errors = validation_errors
            result.error = "Already-satisfied evidence rejected: " + "; ".join(
                validation_errors
            )
            logger.warning(
                "Issue #%d already-satisfied evidence rejected: %s",
                issue.id,
                "; ".join(validation_errors),
            )
            return False

        await self._prs.swap_pipeline_labels(issue.id, self._config.dup_label[0])
        await self._transitioner.post_comment(
            issue.id,
            f"## Already Satisfied\n\n"
            f"The planner determined that this issue's requirements "
            f"are already met by the existing codebase.\n\n"
            f"{result.summary}\n\n"
            f"---\n"
            f"*Generated by HydraFlow Planner*",
        )
        await self._transitioner.close_task(issue.id)
        self._state.record_outcome(
            issue.id,
            IssueOutcomeType.ALREADY_SATISFIED,
            reason=result.summary,
            phase="plan",
        )
        self._state.increment_session_counter("planned")
        logger.info("Issue #%d closed as already satisfied", issue.id)
        if self._summarizer and result.transcript:
            try:
                await self._summarizer.summarize_and_comment(
                    transcript=result.transcript,
                    issue_number=issue.id,
                    phase="plan",
                    status="success",
                    issue_title=issue.title,
                    duration_seconds=result.duration_seconds,
                    log_file=self._plan_log_reference(issue.id),
                )
            except (RuntimeError, OSError):
                logger.exception(
                    "Failed to post transcript summary for issue #%d", issue.id
                )
        return True

    async def _is_product_track_issue(self, issue: Task) -> bool:
        """Detect if an issue came through the product discovery/shape track."""
        enriched = await self._store.enrich_with_comments(issue)
        for comment in enriched.comments or []:
            if "DECOMPOSITION REQUIRED" in comment:
                return True
        return False

    async def _handle_plan_success(self, issue: Task, result: PlanResult) -> None:
        """Post plan comment, run analysis, transition to ready, file sub-issues."""
        # Product-track decomposition check: if issue came from Shape and
        # the planner didn't produce enough sub-issues, retry with feedback
        if (
            await self._is_product_track_issue(issue)
            and len(result.new_issues) < 3
            and not getattr(result, "_decompose_retried", False)
        ):
            logger.info(
                "Issue #%d is product-track but planner only produced %d sub-issues "
                "(need ≥3) — retrying with decomposition feedback",
                issue.id,
                len(result.new_issues),
            )
            retry_result = await self._planners.plan(
                issue,
                research_context=(
                    f"IMPORTANT: This issue came through the product track and "
                    f"MUST be decomposed into 3-8 concrete sub-issues using "
                    f"NEW_ISSUES_START/NEW_ISSUES_END markers. Your previous "
                    f"plan only produced {len(result.new_issues)} sub-issues. "
                    f"Break the work into independently implementable pieces."
                ),
            )
            if retry_result.success and len(retry_result.new_issues) >= 3:
                result = retry_result
            else:
                logger.warning(
                    "Decomposition retry for #%d still insufficient (%d issues)",
                    issue.id,
                    len(retry_result.new_issues) if retry_result.success else 0,
                )
                # Proceed with whatever we have

        branch = self._config.branch_for_issue(issue.id)
        score_line = ""
        if result.actionability_rank != "unknown":
            score_line = (
                f"**Actionability score:** {result.actionability_score}/100 "
                f"({result.actionability_rank})\n"
            )
        # Collect any architecture diagrams the planner wrote to /tmp
        diagram_attachments = PlannerRunner.collect_diagram_attachments(issue.id)
        diagram_section = ""
        if diagram_attachments:
            diagram_section = f"\n\n## Architecture Diagrams\n\n{diagram_attachments}\n"

        comment_body = (
            f"## Implementation Plan\n\n"
            f"{result.plan}\n\n"
            f"{diagram_section}"
            f"**Branch:** `{branch}`\n\n"
            f"---\n"
            f"{score_line}"
            f"*Generated by HydraFlow Planner*"
        )
        await self._transitioner.post_comment(issue.id, comment_body)

        analyzer = PlanAnalyzer(repo_root=self._config.repo_root)
        analysis = analyzer.analyze(result.plan, issue.id)
        await self._transitioner.post_comment(issue.id, analysis.format_comment())

        # Ingest plan knowledge into the per-repo wiki
        await self._wiki_ingest_plan(issue.id, result.plan)

        # Activate eager-transition protection BEFORE the GitHub label swap
        # so that concurrent polling cannot re-queue the issue during the
        # non-atomic label add/remove window.
        self._store.enqueue_transition(issue, "ready")
        await self._transitioner.transition(issue.id, "ready")

        for new_issue in result.new_issues:
            if len(new_issue.body) < _MIN_ISSUE_BODY_CHARS:
                logger.warning(
                    "Skipping discovered issue %r — body too short "
                    "(%d chars, need ≥%d)",
                    new_issue.title,
                    len(new_issue.body),
                    _MIN_ISSUE_BODY_CHARS,
                )
                continue
            labels = new_issue.labels or [self._config.planner_label[0]]
            await self._transitioner.create_task(
                new_issue.title, new_issue.body, labels
            )
            self._state.record_issue_created()

        # Create beads from task graph phases
        if self._beads_manager and result.plan:
            await self._create_beads_from_plan(issue, result.plan)

        if result.duration_seconds > 0:
            self._state.record_plan_duration(result.duration_seconds)
        self._state.increment_session_counter("planned")

        # Mirror the plan into the local JSONL cache with per-issue
        # version counter so plan v1 → v2 → v3 history survives without
        # overwriting comments (#6422). Downstream precondition gates
        # (#6423) and the adversarial plan reviewer (#6421) read this
        # structured record. Best-effort: the cache never raises.
        #
        # findings is intentionally empty on the success path —
        # adversarial findings come from PlanReviewer (#6421) and are
        # written via record_review_stored, not here. Conflating
        # validation_errors with PlanFinding-shaped findings would
        # poison the cache for review-stage consumers expecting the
        # severity/dimension/description schema.
        if self._issue_cache is not None:
            self._issue_cache.record_plan_stored(
                issue.id,
                plan_text=result.plan,
                actionability_score=result.actionability_score,
            )

        logger.info("Plan posted and labels swapped for issue #%d", issue.id)

    _WIKI_INGEST_MAX_CHARS = 40_000

    async def _wiki_ingest_plan(self, issue_number: int, plan_text: str) -> None:
        """Ingest plan knowledge into the per-repo wiki.

        Uses the LLM compiler for synthesis when available, falling back
        to mechanical section extraction.  Skips if already ingested.
        Never raises.
        """
        if self._wiki_store is None or not self._config.repo:
            return
        repo = self._config.repo
        if self._wiki_store.is_ingested(repo, issue_number, "plan"):
            return
        try:
            # Prefer LLM synthesis when compiler is available
            if self._wiki_compiler is not None:
                entries = await self._wiki_compiler.synthesize_ingest(
                    repo,
                    issue_number,
                    "plan",
                    plan_text[: self._WIKI_INGEST_MAX_CHARS],
                )
                if entries:
                    self._wiki_store.ingest(repo, entries)
                    self._wiki_store.mark_ingested(repo, issue_number, "plan")
                    return

            # Fallback: mechanical section extraction
            from repo_wiki_ingest import ingest_from_plan  # noqa: PLC0415

            ingest_from_plan(self._wiki_store, repo, issue_number, plan_text)
            self._wiki_store.mark_ingested(repo, issue_number, "plan")
        except Exception:  # noqa: BLE001
            logger.warning(
                "Wiki ingest failed for plan #%d", issue_number, exc_info=True
            )

    async def _create_beads_from_plan(self, issue: Task, plan: str) -> None:
        """Create bead tasks from a Task Graph plan and post mapping comment."""
        from task_graph import extract_phases  # noqa: PLC0415

        phases = extract_phases(plan)
        if not phases:
            logger.debug(
                "No task graph phases found for issue #%d — skipping beads", issue.id
            )
            return

        assert self._beads_manager is not None  # guarded by caller
        await self._beads_manager.ensure_installed()
        repo_root = self._config.repo_root
        await self._beads_manager.init(repo_root)
        mapping = await self._beads_manager.create_from_phases(
            phases, issue.id, repo_root
        )

        if not mapping:
            logger.warning(
                "Bead creation returned empty mapping for issue #%d", issue.id
            )
            return

        self._state.set_bead_mapping(issue.id, mapping)

        # Post mapping table as issue comment
        rows = "\n".join(f"| {pid} | #{bid} |" for pid, bid in sorted(mapping.items()))
        table = (
            f"## Bead Task Mapping\n\n"
            f"| Phase | Bead ID |\n"
            f"|-------|--------|\n"
            f"{rows}\n\n"
            f"---\n"
            f"*Generated by HydraFlow Planner (beads)*"
        )
        try:
            await self._transitioner.post_comment(issue.id, table)
        except Exception:  # noqa: BLE001
            logger.warning(
                "Failed to post bead mapping comment for issue #%d",
                issue.id,
                exc_info=True,
            )

    async def _handle_plan_failure(self, issue: Task, result: PlanResult) -> None:
        """Post comment, escalate to HITL, record harness failure."""
        error_list = "\n".join(f"- {e}" for e in result.validation_errors)
        score_line = ""
        if result.actionability_rank != "unknown":
            score_line = (
                f"**Actionability score:** {result.actionability_score}/100 "
                f"({result.actionability_rank})\n\n"
            )
        hitl_comment = (
            f"## Plan Validation Failed\n\n"
            f"The planner was unable to produce a valid plan "
            f"after planning attempts for issue #{issue.id}.\n\n"
            f"{score_line}"
            f"**Validation errors:**\n{error_list}\n\n"
            f"---\n"
            f"*Generated by HydraFlow Planner*"
        )
        await self._transitioner.post_comment(issue.id, hitl_comment)
        await self._escalator(
            issue,
            cause="Plan validation failed after retry",
            details="; ".join(result.validation_errors),
            category=FailureCategory.PLAN_VALIDATION,
        )
        logger.warning(
            "Planning failed validation for issue #%d after retry — escalated to HITL",
            issue.id,
        )

    async def _post_plan_transcript(
        self, issue: Task, result: PlanResult, *, status: str
    ) -> None:
        """File memory suggestion and post transcript summary."""
        if result.transcript:
            await self._suggest_memory(
                result.transcript, "planner", f"issue #{issue.id}"
            )
        if self._summarizer and result.transcript:
            try:
                await self._summarizer.summarize_and_comment(
                    transcript=result.transcript,
                    issue_number=issue.id,
                    phase="plan",
                    status=status,
                    issue_title=issue.title,
                    duration_seconds=result.duration_seconds,
                    log_file=self._plan_log_reference(issue.id),
                )
            except (RuntimeError, OSError):
                logger.exception(
                    "Failed to post transcript summary for issue #%d", issue.id
                )

    def _plan_log_reference(self, issue_number: int) -> str:
        """Return a display-friendly log path for planner transcripts."""
        log_path = self._config.log_dir / f"plan-issue-{issue_number}.txt"
        return self._config.format_path_for_display(log_path)

    # ------------------------------------------------------------------
    # Epic group planning helpers
    # ------------------------------------------------------------------

    def _is_epic_child(self, issue: Task) -> bool:
        """Return True if *issue* has an epic-child label."""
        epic_child_labels = {lbl.lower() for lbl in self._config.epic_child_label}
        return bool(epic_child_labels & {t.lower() for t in issue.tags})

    def _resolve_epic_number(self, issue: Task) -> int | None:
        """Extract the parent epic number from metadata or body text."""
        epic_num = issue.metadata.get("epic_number")
        if epic_num:
            return int(epic_num)
        match = re.search(r"[Pp]arent\s+[Ee]pic[:\s#]*(\d+)", issue.body)
        if match:
            return int(match.group(1))
        return None

    def _group_by_epic(
        self, issues: list[Task]
    ) -> tuple[dict[int, list[Task]], list[Task]]:
        """Partition issues into ``{epic_number: [children]}`` and standalone.

        Issues with an epic-child label whose parent cannot be resolved
        are placed in the standalone list.
        """
        epic_groups: dict[int, list[Task]] = {}
        standalone: list[Task] = []
        for issue in issues:
            if not self._is_epic_child(issue):
                standalone.append(issue)
                continue
            epic_num = self._resolve_epic_number(issue)
            if epic_num is None:
                standalone.append(issue)
                continue
            epic_groups.setdefault(epic_num, []).append(issue)
        return epic_groups, standalone

    @staticmethod
    def _parse_gap_review(transcript: str, epic_number: int) -> EpicGapReview:
        """Parse an ``EpicGapReview`` from a gap-review transcript."""
        review = EpicGapReview(epic_number=epic_number)

        start_marker = "GAP_REVIEW_START"
        end_marker = "GAP_REVIEW_END"
        start_idx = transcript.find(start_marker)
        end_idx = transcript.find(end_marker)
        if start_idx == -1:
            return review
        body = transcript[
            start_idx + len(start_marker) : end_idx if end_idx != -1 else None
        ]

        # Extract findings
        findings_match = re.search(
            r"##\s*Findings\s*\n(.*?)(?=\n##|\Z)", body, re.DOTALL
        )
        if findings_match:
            review.findings = findings_match.group(1).strip()

        # Extract re-plan issues
        replan_match = re.search(
            r"##\s*Re-plan Required\s*\n(.*?)(?=\n##|\Z)", body, re.DOTALL
        )
        if replan_match:
            replan_text = replan_match.group(1).strip()
            if replan_text.lower() != "none":
                review.replan_issues = [
                    int(m.group(1)) for m in re.finditer(r"#(\d+)", replan_text)
                ]

        # Extract guidance
        guidance_match = re.search(
            r"##\s*Guidance\s*\n(.*?)(?=\n##|\Z)", body, re.DOTALL
        )
        if guidance_match:
            review.guidance = guidance_match.group(1).strip()

        return review

    async def _plan_one(
        self,
        idx: int,
        issue: Task,
        semaphore: asyncio.Semaphore,
    ) -> PlanResult:
        """Plan a single issue (shared by standalone and epic flows)."""
        if self._stop_event.is_set():
            return PlanResult(issue_number=issue.id, error="stopped")

        async with semaphore:
            if self._stop_event.is_set():
                return PlanResult(issue_number=issue.id, error="stopped")

            with _sentry_transaction("pipeline.plan", f"plan:#{issue.id}"):
                async with store_lifecycle(self._store, issue.id, "plan"):
                    research_context = ""
                    if self._should_research():
                        research_result = await self._research_runner.research(issue)  # type: ignore[union-attr]
                        if research_result.success:
                            research_context = research_result.research
                            logger.info(
                                "Research completed for issue #%d (%d chars)",
                                issue.id,
                                len(research_context),
                            )
                            # Post collapsed research as issue comment
                            try:
                                await self._prs.post_comment(
                                    issue.id,
                                    f"<details><summary>🔬 Research Context</summary>\n\n"
                                    f"{research_context}\n\n</details>",
                                )
                            except Exception:  # noqa: BLE001
                                logger.warning(
                                    "Failed to post research comment for #%d",
                                    issue.id,
                                    exc_info=True,
                                )
                        else:
                            logger.warning(
                                "Research failed for issue #%d: %s",
                                issue.id,
                                research_result.error,
                            )

                    from trace_rollup import write_phase_rollup  # noqa: PLC0415
                    from tracing_context import (  # noqa: PLC0415
                        TracingContext,
                        source_to_phase,
                    )

                    trace_phase = source_to_phase("planner")
                    run_id = self._state.begin_trace_run(issue.id, trace_phase)
                    self._planners.set_tracing_context(
                        TracingContext(
                            issue_number=issue.id,
                            phase=trace_phase,
                            source="planner",
                            run_id=run_id,
                        )
                    )
                    try:
                        result = await self._planners.plan(
                            issue,
                            worker_id=idx,
                            research_context=research_context,
                        )
                    finally:
                        self._planners.clear_tracing_context()
                        try:
                            write_phase_rollup(
                                config=self._config,
                                issue_number=issue.id,
                                phase=trace_phase,
                                run_id=run_id,
                            )
                        except Exception:
                            logger.warning(
                                "Phase rollup failed for issue #%d",
                                issue.id,
                                exc_info=True,
                            )
                        self._state.end_trace_run(issue.id, trace_phase)

                    already_handled = False
                    ts_status = "failed"
                    if result.already_satisfied:
                        # Guard: never auto-close epic children as "already
                        # satisfied" — they were explicitly created as part
                        # of a planned epic and should always get a plan.
                        if self._is_epic_child(issue):
                            logger.warning(
                                "Issue #%d is an epic child — ignoring "
                                "'already satisfied' claim from planner",
                                issue.id,
                            )
                            result.already_satisfied = False
                            result.success = False
                            result.retry_attempted = True
                            result.error = (
                                "Planner claimed already satisfied but issue "
                                "is an epic child — escalating to HITL"
                            )
                            await self._escalator(
                                issue,
                                cause="Epic child falsely claimed already satisfied",
                                details="Epic child claimed already satisfied",
                                category=FailureCategory.PLAN_VALIDATION,
                            )
                            already_handled = True
                            ts_status = "escalated"
                        else:
                            closed = await self._handle_already_satisfied(issue, result)
                            if closed:
                                return result
                            # Evidence validation failed — escalate directly
                            # to HITL (do NOT fall through to _handle_plan_failure
                            # which would post a second misleading comment).
                            await self._escalator(
                                issue,
                                cause="Already-satisfied evidence rejected: "
                                + "; ".join(result.validation_errors),
                                details="; ".join(result.validation_errors),
                                category=FailureCategory.PLAN_VALIDATION,
                            )
                            already_handled = True
                            ts_status = "escalated"

                    if already_handled:
                        pass
                    elif result.success and result.plan:
                        await self._handle_plan_success(issue, result)
                        ts_status = "success"
                    elif result.retry_attempted and result.plan:
                        # Accept the plan despite validation errors — the
                        # implementation agent will handle any stale references
                        # caused by concurrent changes to the codebase.
                        logger.warning(
                            "Plan for issue #%d has validation warnings — "
                            "accepting anyway: %s",
                            issue.id,
                            "; ".join(result.validation_errors),
                        )
                        result.success = True
                        result.validation_errors = []
                        await self._handle_plan_success(issue, result)
                        ts_status = "success"
                    else:
                        logger.warning(
                            "Planning failed for issue #%d — skipping label swap",
                            issue.id,
                        )
                        ts_status = "failed"

                    await self._post_plan_transcript(issue, result, status=ts_status)
                    return result

    def _plan_one_with_context(
        self,
        issue: Task,
        gap_guidance: str,
        sibling_plans: dict[int, str],
    ) -> Task:
        """Return a copy of *issue* with gap feedback appended to comments."""
        sibling_summary = "\n\n".join(
            f"### Sibling Issue #{num}\n{plan[:500]}"
            for num, plan in sibling_plans.items()
            if num != issue.id
        )
        extra_comment = (
            f"## Epic Gap Review Feedback\n\n"
            f"{gap_guidance}\n\n"
            f"## Sibling Plan Summaries\n\n"
            f"{sibling_summary}"
        )
        return issue.model_copy(update={"comments": [*issue.comments, extra_comment]})

    async def _post_gap_review_comment(
        self, epic_number: int, review: EpicGapReview, iteration: int
    ) -> None:
        """Post gap review findings as a comment on the epic issue."""
        replan_list = (
            ", ".join(f"#{n}" for n in review.replan_issues)
            if review.replan_issues
            else "None"
        )
        comment = (
            f"## Epic Gap Review (Iteration {iteration})\n\n"
            f"**Findings:**\n{review.findings}\n\n"
            f"**Re-plan required:** {replan_list}\n\n"
            f"**Guidance:**\n{review.guidance}\n\n"
            f"---\n"
            f"*Generated by HydraFlow Planner*"
        )
        await self._transitioner.post_comment(epic_number, comment)

    async def _plan_epic_group(
        self,
        epic_number: int,
        children: list[Task],
        semaphore: asyncio.Semaphore,
    ) -> list[PlanResult]:
        """Plan all children of an epic with gap review and re-planning."""
        logger.info(
            "Planning epic #%d group (%d children)",
            epic_number,
            len(children),
        )

        # Phase 1: plan all children concurrently
        results = await run_concurrent_batch(
            children,
            lambda idx, issue: self._plan_one(idx, issue, semaphore),
            self._stop_event,
        )

        # Collect successful plans
        plan_map: dict[int, str] = {}
        title_map: dict[int, str] = {}
        issue_map: dict[int, Task] = {c.id: c for c in children}
        for r in results:
            if r.success and r.plan:
                plan_map[r.issue_number] = r.plan
                issue = issue_map.get(r.issue_number)
                title_map[r.issue_number] = issue.title if issue else ""
                r.epic_number = epic_number

        # Skip gap review if fewer than 2 successful plans
        max_iterations = self._config.epic_gap_review_max_iterations
        if len(plan_map) < 2 or max_iterations == 0:
            logger.info(
                "Epic #%d: skipping gap review (%d plans, max_iter=%d)",
                epic_number,
                len(plan_map),
                max_iterations,
            )
            return results

        # Phase 2: gap review loop
        for iteration in range(1, max_iterations + 1):
            if self._stop_event.is_set():
                break

            logger.info(
                "Epic #%d: gap review iteration %d/%d",
                epic_number,
                iteration,
                max_iterations,
            )
            transcript = await self._planners.run_gap_review(
                epic_number, plan_map, title_map
            )
            review = self._parse_gap_review(transcript, epic_number)

            if not review.replan_issues:
                logger.info(
                    "Epic #%d: plans are coherent after iteration %d",
                    epic_number,
                    iteration,
                )
                break

            await self._post_gap_review_comment(epic_number, review, iteration)

            # Re-plan flagged children with gap context
            for issue_number in review.replan_issues:
                if self._stop_event.is_set():
                    break
                issue = issue_map.get(issue_number)
                if issue is None:
                    logger.warning(
                        "Epic #%d: gap review flagged #%d but not in group",
                        epic_number,
                        issue_number,
                    )
                    continue

                enriched = self._plan_one_with_context(issue, review.guidance, plan_map)
                replan_result = await self._plan_one(0, enriched, semaphore)
                if replan_result.success and replan_result.plan:
                    plan_map[issue_number] = replan_result.plan
                    replan_result.epic_number = epic_number
                # Update the results list
                results = [
                    replan_result if r.issue_number == issue_number else r
                    for r in results
                ]

        return results

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    async def plan_issues(self) -> list[PlanResult]:
        """Run planning agents on issues from the plan queue.

        Uses a slot-filling pool so new issues are picked up as soon
        as a planner slot frees, rather than waiting for the full batch.
        Epic children are still grouped and planned together when
        ``epic_group_planning`` is enabled.
        """
        semaphore = asyncio.Semaphore(self._config.max_planners)

        # If epic grouping is enabled, drain a batch first to identify
        # epic children, then plan them as groups.
        epic_results: list[PlanResult] = []
        if self._config.epic_group_planning:
            batch = self._store.get_plannable(2 * self._config.max_planners)
            if batch:
                epic_groups, standalone = self._group_by_epic(batch)
                # Re-queue standalone issues for the pool below
                for issue in standalone:
                    self._store.enqueue_transition(issue, "plan")
                release_batch_in_flight(self._store, {i.id for i in standalone})

                for epic_number, children in epic_groups.items():
                    if self._stop_event.is_set():
                        break
                    try:
                        results = await self._plan_epic_group(
                            epic_number, children, semaphore
                        )
                        epic_results.extend(results)
                        if self._epic_manager is not None:
                            for r in results:
                                if r.success and r.plan:
                                    await self._epic_manager.on_child_planned(
                                        epic_number, r.issue_number
                                    )
                    finally:
                        release_batch_in_flight(self._store, {c.id for c in children})

        async def _plan_worker(idx: int, issue: Task) -> PlanResult:
            try:
                return await self._plan_one(idx, issue, semaphore)
            finally:
                release_batch_in_flight(self._store, {issue.id})

        standalone_results = await run_refilling_pool(
            supply_fn=lambda: self._store.get_plannable(1),
            worker_fn=_plan_worker,
            max_concurrent=self._config.max_planners,
            stop_event=self._stop_event,
        )

        return epic_results + standalone_results
