"""Plan phase — run planning agents on issues and post results."""

from __future__ import annotations

import asyncio
import logging

from analysis import PlanAnalyzer
from config import HydraFlowConfig
from events import EventBus
from harness_insights import FailureCategory, HarnessInsightStore
from issue_store import IssueStore
from models import PipelineStage, PlanResult, Task
from phase_utils import (
    escalate_to_hitl,
    record_harness_failure,
    release_batch_in_flight,
    run_concurrent_batch,
    safe_file_memory_suggestion,
    store_lifecycle,
)
from planner import PlannerRunner
from pr_manager import PRManager
from state import StateTracker
from task_source import TaskTransitioner
from transcript_summarizer import TranscriptSummarizer

logger = logging.getLogger("hydraflow.plan_phase")

# Minimum body length for auto-filed sub-issues discovered during planning.
_MIN_ISSUE_BODY_CHARS: int = 50


class PlanPhase:
    """Runs planning agents on issues and posts results."""

    def __init__(
        self,
        config: HydraFlowConfig,
        state: StateTracker,
        store: IssueStore,
        planners: PlannerRunner,
        prs: PRManager,
        event_bus: EventBus,
        stop_event: asyncio.Event,
        transcript_summarizer: TranscriptSummarizer | None = None,
        harness_insights: HarnessInsightStore | None = None,
    ) -> None:
        self._config = config
        self._state = state
        self._store = store
        self._planners = planners
        self._prs = prs
        self._transitioner: TaskTransitioner = prs
        self._bus = event_bus
        self._stop_event = stop_event
        self._summarizer = transcript_summarizer
        self._harness_insights = harness_insights

    async def _handle_already_satisfied(self, issue: Task, result: PlanResult) -> None:
        """Close issue as already-satisfied: swap label, post comment, close."""
        await self._prs.swap_pipeline_labels(issue.id, self._config.dup_label[0])
        await self._transitioner.post_comment(
            issue.id,
            f"## Already Satisfied\n\n"
            f"The planner determined that this issue's requirements "
            f"are already met by the existing codebase.\n\n"
            f"{result.summary}\n\n"
            f"---\n"
            f"*Generated by HydraFlow Planner*",
        )
        await self._transitioner.close_task(issue.id)
        logger.info("Issue #%d closed as already satisfied", issue.id)
        if self._summarizer and result.transcript:
            try:
                await self._summarizer.summarize_and_comment(
                    transcript=result.transcript,
                    issue_number=issue.id,
                    phase="plan",
                    status="success",
                    issue_title=issue.title,
                    duration_seconds=result.duration_seconds,
                    log_file=self._plan_log_reference(issue.id),
                )
            except Exception:
                logger.exception(
                    "Failed to post transcript summary for issue #%d", issue.id
                )

    async def _handle_plan_success(self, issue: Task, result: PlanResult) -> None:
        """Post plan comment, run analysis, transition to ready, file sub-issues."""
        branch = self._config.branch_for_issue(issue.id)
        score_line = ""
        if result.actionability_rank != "unknown":
            score_line = (
                f"**Actionability score:** {result.actionability_score}/100 "
                f"({result.actionability_rank})\n"
            )
        comment_body = (
            f"## Implementation Plan\n\n"
            f"{result.plan}\n\n"
            f"**Branch:** `{branch}`\n\n"
            f"---\n"
            f"{score_line}"
            f"*Generated by HydraFlow Planner*"
        )
        await self._transitioner.post_comment(issue.id, comment_body)

        analyzer = PlanAnalyzer(repo_root=self._config.repo_root)
        analysis = analyzer.analyze(result.plan, issue.id)
        await self._transitioner.post_comment(issue.id, analysis.format_comment())
        await self._transitioner.transition(issue.id, "ready")
        self._store.enqueue_transition(issue, "ready")

        for new_issue in result.new_issues:
            if len(new_issue.body) < _MIN_ISSUE_BODY_CHARS:
                logger.warning(
                    "Skipping discovered issue %r — body too short "
                    "(%d chars, need ≥%d)",
                    new_issue.title,
                    len(new_issue.body),
                    _MIN_ISSUE_BODY_CHARS,
                )
                continue
            labels = new_issue.labels or [self._config.planner_label[0]]
            await self._transitioner.create_task(
                new_issue.title, new_issue.body, labels
            )
            self._state.record_issue_created()

        logger.info("Plan posted and labels swapped for issue #%d", issue.id)

    async def _handle_plan_failure(self, issue: Task, result: PlanResult) -> None:
        """Post comment, escalate to HITL, record harness failure."""
        error_list = "\n".join(f"- {e}" for e in result.validation_errors)
        score_line = ""
        if result.actionability_rank != "unknown":
            score_line = (
                f"**Actionability score:** {result.actionability_score}/100 "
                f"({result.actionability_rank})\n\n"
            )
        hitl_comment = (
            f"## Plan Validation Failed\n\n"
            f"The planner was unable to produce a valid plan "
            f"after two attempts for issue #{issue.id}.\n\n"
            f"{score_line}"
            f"**Validation errors:**\n{error_list}\n\n"
            f"---\n"
            f"*Generated by HydraFlow Planner*"
        )
        await self._transitioner.post_comment(issue.id, hitl_comment)
        await escalate_to_hitl(
            self._state,
            self._prs,
            issue.id,
            cause="Plan validation failed after retry",
            origin_label=self._config.planner_label[0],
            hitl_label=self._config.hitl_label[0],
        )
        self._store.enqueue_transition(issue, "hitl")
        record_harness_failure(
            self._harness_insights,
            issue.id,
            FailureCategory.PLAN_VALIDATION,
            "; ".join(result.validation_errors),
            stage=PipelineStage.PLAN,
        )
        logger.warning(
            "Planning failed validation for issue #%d after retry — escalated to HITL",
            issue.id,
        )

    async def _post_plan_transcript(
        self, issue: Task, result: PlanResult, *, status: str
    ) -> None:
        """File memory suggestion and post transcript summary."""
        if result.transcript:
            await safe_file_memory_suggestion(
                result.transcript,
                "planner",
                f"issue #{issue.id}",
                self._config,
                self._prs,
                self._state,
            )
        if self._summarizer and result.transcript:
            try:
                await self._summarizer.summarize_and_comment(
                    transcript=result.transcript,
                    issue_number=issue.id,
                    phase="plan",
                    status=status,
                    issue_title=issue.title,
                    duration_seconds=result.duration_seconds,
                    log_file=self._plan_log_reference(issue.id),
                )
            except Exception:
                logger.exception(
                    "Failed to post transcript summary for issue #%d", issue.id
                )

    def _plan_log_reference(self, issue_id: int) -> str:
        """Return a display-friendly log path for planner transcripts."""
        log_path = self._config.log_dir / f"plan-issue-{issue_id}.txt"
        return self._config.format_path_for_display(log_path)

    async def plan_issues(self) -> list[PlanResult]:
        """Run planning agents on issues from the plan queue."""
        issues = self._store.get_plannable(self._config.batch_size)
        if not issues:
            return []

        semaphore = asyncio.Semaphore(self._config.max_planners)

        async def _plan_one(idx: int, issue: Task) -> PlanResult:
            if self._stop_event.is_set():
                return PlanResult(issue_number=issue.id, error="stopped")

            async with semaphore:
                if self._stop_event.is_set():
                    return PlanResult(issue_number=issue.id, error="stopped")

                async with store_lifecycle(self._store, issue.id, "plan"):
                    result = await self._planners.plan(issue, worker_id=idx)

                    if result.already_satisfied:
                        # Guard: never auto-close epic children as "already
                        # satisfied" — they were explicitly created as part
                        # of a planned epic and should always get a plan.
                        epic_child_labels = {
                            lbl.lower() for lbl in self._config.epic_child_label
                        }
                        issue_labels = {t.lower() for t in issue.tags}
                        if epic_child_labels & issue_labels:
                            logger.warning(
                                "Issue #%d is an epic child — ignoring "
                                "'already satisfied' claim from planner",
                                issue.id,
                            )
                            result.already_satisfied = False
                            result.success = False
                            result.error = (
                                "Planner claimed already satisfied but issue "
                                "is an epic child — forcing plan retry"
                            )
                        else:
                            await self._handle_already_satisfied(issue, result)
                            return result

                    if result.success and result.plan:
                        await self._handle_plan_success(issue, result)
                        ts_status = "success"
                    elif result.retry_attempted:
                        await self._handle_plan_failure(issue, result)
                        ts_status = "escalated"
                    else:
                        logger.warning(
                            "Planning failed for issue #%d — skipping label swap",
                            issue.id,
                        )
                        ts_status = "failed"

                    await self._post_plan_transcript(issue, result, status=ts_status)
                    return result

        try:
            return await run_concurrent_batch(issues, _plan_one, self._stop_event)
        finally:
            release_batch_in_flight(self._store, {i.id for i in issues})

    def _record_harness_failure(
        self,
        issue_number: int,
        category: FailureCategory,
        details: str,
    ) -> None:
        """Delegate to :func:`phase_utils.record_harness_failure` (backward compat)."""
        record_harness_failure(
            self._harness_insights,
            issue_number,
            category,
            details,
            stage=PipelineStage.PLAN,
        )
