"""SandboxFailureFixerLoop — auto-agent self-fix for failed sandbox CI.

Caretaker loop that polls open PRs labeled ``sandbox-fail-auto-fix`` and
dispatches :class:`AutoAgentRunner` to fix the underlying scenario failure.

After ``auto_agent_max_attempts`` unsuccessful attempts the loop swaps the
label set: ``sandbox-fail-auto-fix`` → ``sandbox-hitl`` so the PR surfaces
in the System tab HITL queue (via ``/api/sandbox-hitl``, added in Task 3.13).

The ``no-auto-fix`` label is the operator opt-out: PRs carrying it are
skipped entirely (neither dispatched nor escalated).

Generated by ``scripts/scaffold_loop.py`` on 2026-04-28; body filled in for
Task 3.12 of the sandbox-tier scenario testing track.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

from base_background_loop import BaseBackgroundLoop, LoopDeps
from config import HydraFlowConfig
from exception_classify import reraise_on_credit_or_bug

if TYPE_CHECKING:
    from ports import PRPort
    from preflight.auto_agent_runner import AutoAgentRunner
    from state import StateTracker

logger = logging.getLogger("hydraflow.sandbox_failure_fixer")

_AUTO_FIX_LABEL = "sandbox-fail-auto-fix"
_HITL_LABEL = "sandbox-hitl"
_OPT_OUT_LABEL = "no-auto-fix"


class SandboxFailureFixerLoop(BaseBackgroundLoop):
    """Auto-fixes promotion PRs failing sandbox CI by dispatching the auto-agent.

    Polls ``PRPort.list_prs_by_label('sandbox-fail-auto-fix')`` once per tick.
    For each candidate that is not opted out via ``no-auto-fix``:

    * If attempts < ``auto_agent_max_attempts``, bump the counter and call
      ``runner.run`` with the ``prompts/auto_agent/sandbox_fix.md`` envelope.
    * Otherwise swap labels (``sandbox-fail-auto-fix`` → ``sandbox-hitl``)
      so the PR shows up in the HITL queue for human triage.

    Ships kill-switched-off via the universal ADR-0049 mandate plus the
    ``HYDRAFLOW_SANDBOX_FAILURE_FIXER_ENABLED`` static config gate.
    """

    def __init__(
        self,
        *,
        config: HydraFlowConfig,
        state: StateTracker | Any,
        deps: LoopDeps,
        prs: PRPort | Any | None = None,
        runner: AutoAgentRunner | Any | None = None,
    ) -> None:
        super().__init__(
            worker_name="sandbox_failure_fixer",
            config=config,
            deps=deps,
            run_on_startup=False,
        )
        self._state = state
        self._prs = prs
        self._runner = runner

    def _get_default_interval(self) -> int:
        return self._config.sandbox_failure_fixer_interval

    async def _do_work(self) -> dict[str, Any] | None:
        # ADR-0049 in-body kill-switch (universal mandate).
        if not self._enabled_cb(self._worker_name):
            return {"status": "disabled"}

        # Static config gate (defense-in-depth: deploy-time disable).
        if not self._config.sandbox_failure_fixer_enabled:
            return {"status": "config_disabled"}

        if self._prs is None or self._runner is None:
            # Defensive: scaffold-only construction (e.g. tests/scenarios) that
            # never wired the PR port or runner. Treat as a no-op rather than
            # crashing.
            return {"status": "ok", "candidates": 0}

        prs = self._prs
        runner = self._runner
        assert prs is not None and runner is not None  # noqa: S101  # type narrow
        candidates = await prs.list_prs_by_label(_AUTO_FIX_LABEL)
        max_attempts = int(self._config.auto_agent_max_attempts)

        dispatched = 0
        escalated = 0
        crashed = 0
        skipped_opt_out = 0

        for pr in candidates:
            labels = list(getattr(pr, "labels", []) or [])
            if _OPT_OUT_LABEL in labels:
                logger.info(
                    "PR #%d carries %s; skipping auto-fix",
                    pr.number,
                    _OPT_OUT_LABEL,
                )
                skipped_opt_out += 1
                continue

            attempts = self._state.get_sandbox_failure_fixer_attempts(pr.number)
            if attempts >= max_attempts:
                logger.warning(
                    "PR #%d hit auto-fix cap (%d) — escalating to HITL",
                    pr.number,
                    attempts,
                )
                try:
                    await prs.remove_pr_label(pr.number, _AUTO_FIX_LABEL)
                    await prs.add_pr_labels(pr.number, [_HITL_LABEL])
                except Exception as exc:
                    reraise_on_credit_or_bug(exc)
                    logger.warning("label-swap failed for PR #%d: %s", pr.number, exc)
                else:
                    escalated += 1
                continue

            # Bump attempts BEFORE spawning so a crashed/timed-out runner still
            # counts toward the cap (matches AutoAgentPreflightLoop).
            attempt_n = self._state.bump_sandbox_failure_fixer_attempts(pr.number)
            try:
                outcome = await runner.run(
                    prompt=self._build_prompt(pr),
                    worktree_path=str(getattr(pr, "branch", "")),
                    issue_number=int(pr.number),
                )
            except Exception as exc:
                reraise_on_credit_or_bug(exc)
                logger.warning(
                    "auto-fix attempt %d failed for PR #%d: %s",
                    attempt_n,
                    pr.number,
                    exc,
                )
                continue

            if getattr(outcome, "crashed", False):
                logger.warning(
                    "auto-agent crashed on PR #%d (attempt %d)",
                    pr.number,
                    attempt_n,
                )
                crashed += 1
            else:
                dispatched += 1

        return {
            "status": "ok",
            "candidates": len(candidates),
            "dispatched": dispatched,
            "escalated": escalated,
            "crashed": crashed,
            "skipped_opt_out": skipped_opt_out,
        }

    def _build_prompt(self, pr: Any) -> str:
        """Render the ``sandbox_fix.md`` envelope with this PR's context."""
        from pathlib import Path

        envelope_path = (
            Path(__file__).resolve().parent.parent
            / "prompts"
            / "auto_agent"
            / "sandbox_fix.md"
        )
        envelope = envelope_path.read_text()
        return envelope.replace("{PR_NUMBER}", str(pr.number)).replace(
            "{PR_BRANCH}", str(getattr(pr, "branch", ""))
        )
