"""Term-Pruner Loop — caretaker that deprecates terms with broken anchors.

See ADR-0057 and docs/superpowers/specs/2026-05-08-term-pruner-loop-design.md.
"""

from __future__ import annotations

import logging
import secrets
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

from base_background_loop import BaseBackgroundLoop, LoopDeps
from term_proposer_loop import BotPRPort, _render_term_file_str
from ubiquitous_language import (
    Term,
    TermStore,
    _slugify_term_name,
    build_symbol_index,
    resolve_anchor,
)

if TYPE_CHECKING:
    from config import HydraFlowConfig


logger = logging.getLogger("hydraflow.term_pruner_loop")


_WORKER_NAME = "term_pruner"
TERM_PRUNER_PR_LABEL = "hydraflow-ul-deprecated"
"""Label applied to bot-PRs opened by ``TermPrunerLoop``.

Public constant — imported by ``review_phase`` to skip routing such PRs through
the agent pipeline (the auto-deprecation PR is purely structural). See ADR-0057.
"""


class TermPrunerLoop(BaseBackgroundLoop):
    """Periodically scans existing terms; deprecates those with broken anchors."""

    def __init__(
        self,
        *,
        config: HydraFlowConfig,
        deps: LoopDeps,
        pr_port: BotPRPort,
        repo_root: Path,
    ) -> None:
        super().__init__(worker_name=_WORKER_NAME, config=config, deps=deps)
        self._pr_port = pr_port
        self._repo_root = repo_root

    def _get_default_interval(self) -> int:
        return self._config.term_pruner_interval

    async def _do_work(self) -> dict[str, Any] | None:
        # Canonical operator UI kill-switch (ADR-0049).
        if not self._enabled_cb(self._worker_name):
            return {"status": "disabled"}
        # Static config gate — defense-in-depth (slice #5.0).
        if not self._config.term_pruner_enabled:
            return {"status": "disabled"}

        terms_root = self._repo_root / "docs" / "wiki" / "terms"
        src_root = self._repo_root / "src"

        store = TermStore(terms_root)
        terms = store.list()
        index = build_symbol_index(src_root)

        candidates: list[Term] = []
        for term in terms:
            if term.confidence != "accepted":
                continue
            if term.superseded_by is not None:
                continue
            if resolve_anchor(term.code_anchor, index):
                continue
            candidates.append(term)

        if not candidates:
            return {
                "status": "ok",
                "checked": len(terms),
                "deprecated": 0,
                "opened_pr": False,
            }

        now_iso = datetime.now(UTC).isoformat()
        deprecated_terms: list[Term] = []
        for term in candidates:
            data = term.model_dump()
            data["confidence"] = "deprecated"
            data["superseded_reason"] = (
                f"anchor {term.code_anchor!r} no longer resolves "
                f"(auto-deprecated by TermPrunerLoop on {now_iso})"
            )
            data["updated_at"] = now_iso
            deprecated_terms.append(Term.model_validate(data))

        run_id = secrets.token_hex(4)
        files: dict[str, str] = {}
        for term in deprecated_terms:
            slug = _slugify_term_name(term.name)
            rel_path = str(Path("docs/wiki/terms") / f"{slug}.md")
            files[rel_path] = _render_term_file_str(term)

        title = (
            f"feat(ul): term-pruner — {len(deprecated_terms)} terms "
            "deprecated (broken anchors)"
        )
        body_lines = [
            "Auto-generated batch from `TermPrunerLoop` (ADR-0057).",
            "",
            "Terms in this PR have `code_anchor` values that no longer resolve in `src/` —",
            "the anchored class was deleted or renamed. Each is flipped to "
            "`confidence: deprecated` with a `superseded_reason` documenting the broken anchor.",
            "",
            "Deprecated:",
        ]
        for term in deprecated_terms:
            body_lines.append(
                f"- **{term.name}** ({term.kind.value}, {term.bounded_context.value})"
                f" — `{term.code_anchor}` (no longer resolves)"
            )
        body_lines += [
            "",
            "Auto-merge on CI green via `DependabotMergeLoop`.",
            "",
            "Generated by `TermPrunerLoop`",
        ]

        pr_number = await self._pr_port.open_bot_pr(
            branch=f"ul-pruner/{run_id}",
            title=title,
            body="\n".join(body_lines),
            labels=[TERM_PRUNER_PR_LABEL],
            files=files,
        )

        return {
            "status": "ok",
            "checked": len(terms),
            "deprecated": len(deprecated_terms),
            "opened_pr": pr_number is not None,
        }
