"""Term-Proposer Loop — caretaker that grows the ubiquitous-language glossary.

See ADR-0054 and docs/superpowers/specs/2026-05-06-term-proposer-loop-design.md.

This file's responsibilities:
- open_proposer_pr: bot-PR helper (used by the loop, but separable for testing)
- TermProposerLoop: the BaseBackgroundLoop subclass (added in Task 8)
"""

from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Protocol

from ubiquitous_language import (
    Term,
    _slugify_term_name,  # noqa: F401
    dump_term_file,
)


class BotPRPort(Protocol):
    """Minimal interface for opening bot PRs. Subset of PRPort.

    Production wiring will pass the project's existing PRPort adapter; tests pass a fake.
    """

    async def open_bot_pr(
        self,
        *,
        branch: str,
        title: str,
        body: str,
        labels: list[str],
        files: dict[str, str],
    ) -> int: ...


_PR_LABEL = "hydraflow-ul-proposed"


async def open_proposer_pr(
    *,
    terms: list[Term],
    run_id: str,
    port: BotPRPort,
    terms_root: Path,
) -> int | None:
    """Render N terms to file content, open one bundled PR, return PR number or None."""
    if not terms:
        return None

    files: dict[str, str] = {}
    for term in terms:
        slug = _slugify_term_name(term.name)
        rel_path = str(terms_root / f"{slug}.md")
        files[rel_path] = _render_term_file_str(term)

    title = f"feat(ul): term-proposer batch — {len(terms)} drafts"
    body_lines = [
        "Auto-generated batch from `TermProposerLoop` (ADR-0054).",
        "",
        "Drafts in this PR:",
    ]
    for term in terms:
        body_lines.append(
            f"- **{term.name}** ({term.kind.value}, {term.bounded_context.value})"
            f" — `{term.code_anchor}`"
            + (
                f" · imports_seen={term.proposal_imports_seen}"
                if term.proposal_imports_seen is not None
                else ""
            )
        )
    body_lines += [
        "",
        "Each term ships as `confidence: proposed`. The Confidence-Promoter loop ages",
        "`proposed` → `accepted` once stable. Auto-merge on CI green via",
        "`DependabotMergeLoop`.",
        "",
        "🤖 Generated by `TermProposerLoop`",
    ]

    return await port.open_bot_pr(
        branch=f"ul-proposer/{run_id}",
        title=title,
        body="\n".join(body_lines),
        labels=[_PR_LABEL],
        files=files,
    )


def _render_term_file_str(term: Term) -> str:
    """Render a Term to its on-disk markdown form as a string.

    Reuses dump_term_file via a tempfile so the on-disk format stays canonical.
    """
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", delete=False, encoding="utf-8"
    ) as f:
        tmp_path = Path(f.name)
    try:
        dump_term_file(tmp_path, term)
        return tmp_path.read_text(encoding="utf-8")
    finally:
        tmp_path.unlink(missing_ok=True)
